### ISSUE TITLE
How to hard code a customized flow ?

### ISSUE THREAD

**Issue by mehul-m-prajapati** [NorthboundNetworks/ZodiacFX#74]
Hi,

I want to aggregate traffic from port 1 & 2 to port 3 in the Zodiac switch.

I don't want to use SDN controller.

Is it possible to make code changes in firmware to do that ?

Thanks,
Mehul

**Comment by pzanna** [comment]
Hi Mehul,

I answered your question on the forum.

Regards,
Paul

**Comment by mehul-m-prajapati** [comment]
Hi Paul,

Thanks for your answer. I appreciated it.

Regards,
Mehul
